### ISSUE TITLE
Ability to define owner for arbitrary classes

### ISSUE THREAD

**Issue by fatkodima** [ankane/ownership#9]
There are native active job and controllers integration within this gem, which set callbacks accordingly. For other use cases, it is possible to use a block version of the `owner` method call. 

I want to integrate it into sidekiq jobs. There are no callbacks, like in activejob. For example, I can have a job:
```ruby
class MyJob
  include Sidekiq::Job
  owner :payments

  def perform
  end
end
```
and I need to create a custom server middleware (https://github.com/sidekiq/sidekiq/wiki/Middleware), which will look something like:
```ruby
class SetOwnerMiddleware
  def call(job_instance, job_payload, queue, &block)
    owner(job_instance.class.owner, &block)
  end
end
```

Note, that I need to somehow get the owner of the job class. 

I also want to be able to use `owner` definitions in other places, like models. Something like:
```ruby
class SomeModel < ApplicationRecord
  owner :payments
end
```

so people can easily find who is the owner of the class and I can enforce via a custom rubocop rule to have such declarations on specific classes.

So, are you open for changing https://github.com/ankane/ownership/blob/105460e7dd8d99e0a7640fe1faeb38767ef286a5/lib/ownership/global_methods.rb#L11 and adding `attr_reader` to be able to get an owner from the class?

**Comment by ankane** [comment]
Hi @fatkodima, it isn't something I'd like to include (as it wouldn't behave the same as `owner` on controllers and jobs), but you could define an `owner` method on `Class` to do this.
